services:
  marvelapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__PostgresConnection=${ConnectionStrings__PostgresConnection}
      - MySecretKey=${MySecretKey}
    networks:
      - marvelapi-network
    env_file:
      - stack.env
networks:
  marvelapi-network:
    external: true