services:
  marvelapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__PostgresConnection=${ConnectionStrings__PostgresConnection}
      - MySecretKey=${MySecretKey}
    networks:
      - marvelapi-network
    volumes:
      - ${ENV_FILE}:/app/.env
networks:
  marvelapi-network:
    external: true